# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Njv0iqk_MirmUv1F42xcr4OYGKLTLj2i
"""

#PYTHON ASSIGNMENT-2 WORK ON r+,W+,A+
#""r+" (Read and Write Mode):
#Meaning: This mode allows both reading from and writing to the file. It opens the file for both reading and writing, starting at the beginning of the file.
#Example:
file = open("abc.txt", "r+")
content = file.read()
print(content)
file.write("New content")
file.close()

#"w+" (Write and Read Mode):
#Meaning: This mode allows both writing to and reading from the file. It opens the file for both writing and reading, and if the file already exists, it will truncate it (i.e., clear the file content). If the file doesn't exist, a new file will be created.
#EXAMPLE
file = open("abc.txt", "w+")
file.write("Hello, World!")
file.seek(0)
content = file.read()
print(content)
file.close()

#"a+" (Append and Read Mode):
#Meaning: This mode allows both appending to and reading from the file. It opens the file for both appending and reading. If the file exists, the writing will start at the end of the file; if the file doesn't exist, a new file will be created.
#Example:
file = open("example.txt", "a+")
file.write("Hello, World!")
file.seek(0)
content = file.read()
print(content)
file.close()